# Generated by Django 3.1.4 on 2021-01-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210119_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
