# Generated by Django 3.1.4 on 2021-01-19 20:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210119_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
