# Generated by Django 3.1.4 on 2021-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210119_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='com_id',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='id',
            new_name='vacancy_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='com_id',
            field=models.PositiveIntegerField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_id',
            field=models.PositiveIntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
