# Generated by Django 3.1.4 on 2021-01-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210123_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='apply_id',
            field=models.PositiveIntegerField(auto_created=True,
                                              db_column='id',
                                              default=1,
                                              primary_key=True,
                                              serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='150x80.gif', upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='150x150.gif', upload_to='speciality_images'),
        ),
    ]
