# Generated by Django 3.1.4 on 2021-01-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20210127_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
