# Generated by Django 3.1.4 on 2021-01-31 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0010_auto_20210130_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='com_id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='companies',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
